# Generated by Django 4.2.7 on 2023-12-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('info', models.CharField(max_length=128)),
            ],
        ),
    ]
