# Generated by Django 4.2.7 on 2023-12-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_userexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpenses',
            name='date',
            field=models.DateField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userexpenses',
            name='amount',
            field=models.FloatField(),
        ),
    ]
