# Generated by Django 4.2.7 on 2023-12-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_userexpenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpenses',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
