# Generated by Django 4.2.7 on 2023-12-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_userexpenses_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexpenses',
            name='date',
        ),
    ]
