# Generated by Django 4.2.7 on 2023-12-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_userexpenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpenses',
            name='date',
            field=models.DateField(),
        ),
    ]
