# Generated by Django 4.2.7 on 2023-12-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_userexpenses_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExpenses',
        ),
    ]
